# Generated by Django 3.0.8 on 2020-07-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='year_created',
            field=models.IntegerField(default=2020),
        ),
    ]
