# Generated by Django 3.0.8 on 2020-07-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_artpiece_year_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='artPiece',
        ),
    ]
