# Generated by Django 3.0.8 on 2020-07-28 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='artPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('yearCreated', models.IntegerField(default=2020)),
                ('medium', models.CharField(max_length=20)),
                ('image', models.FilePathField(path='/img')),
                ('belongsTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.collection')),
            ],
        ),
    ]
